### ISSUE TITLE
if possible then replace mee6 by add server-log feature

### ISSUE THREAD

**Issue by KunalSin9h** [KunalSin9h/coptit-bot#11]

**Comment by KunalSin9h** [comment]
This is possible

**Comment by KunalSin9h** [comment]
thinks to look for 
1 Text channel created (voice, etc...)
2 Category created
3 Role updated
4  Role deleted
5 Channel permissions updated
6 Roel created
7 Server information updated!
and counting....

**Comment by anjali29singh** [comment]
yes good

**Comment by KunalSin9h** [comment]
done
